
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 15 02:05:44 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 33;
  public static final int CHAR = 21;
  public static final int SLASH = 42;
  public static final int GRT = 29;
  public static final int CONTINUE = 40;
  public static final int LPAREN = 7;
  public static final int SEMI = 5;
  public static final int LSS = 31;
  public static final int MINUS = 14;
  public static final int STAR = 41;
  public static final int RPAREN = 8;
  public static final int GRE = 30;
  public static final int AND = 25;
  public static final int RECORD = 35;
  public static final int OR = 26;
  public static final int BOOL = 20;
  public static final int COMMA = 15;
  public static final int CLASS = 34;
  public static final int PLUS = 13;
  public static final int IF = 23;
  public static final int DOT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 11;
  public static final int SUPER = 45;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int PERCENT = 43;
  public static final int NUMBER = 19;
  public static final int NEQ = 28;
  public static final int BREAK = 39;
  public static final int IDENT = 22;
  public static final int VOID = 18;
  public static final int EQ = 27;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int READ = 16;
  public static final int WHILE = 38;
  public static final int LSSE = 32;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 44;
  public static final int PROG = 2;
  public static final int DO = 37;
  public static final int PRINT = 17;
}

